import dotenv from "dotenv";
dotenv.config();

export const {
  PORT,
  MONGO_URI,
  JWT_ACCESS_SECRET,
  JWT_REFRESH_SECRET,
  CLIENT_URL,
  // EMAIL_HOST,
  // EMAIL_PORT,
  // EMAIL_USER,
  // EMAIL_PASS,
  EMAIL_FROM,
  APP_URL,
  MJ_API_KEY,
  MJ_API_SECRET,
  TICKETMASTER_API_KEY,
  OPENAI_API_KEY,
  MAPTILER_KEY,
  // RESEND_API_KEY,
  MAPBOX_TOKEN,
  UNSPLASH_ACCESS_KEY,
} = process.env;
